---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es
sidebar:
  entries:
  - title: Documentation StorageGRID
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrir vos systèmes StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Gestion des systèmes StorageGRID
    entries:
    - title: Afficher vos systèmes StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Faites confiance aux services de données NetApp avec StorageGRID
      url: "/task-enable-data-services.html"
    - title: Supprimer les systèmes StorageGRID
      url: "/task-remove-storagegrid.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrir vos systèmes StorageGRID
      url: task-discover-storagegrid.html
  - title: Gestion des systèmes StorageGRID
    links:
    - title: Afficher vos systèmes StorageGRID
      url: task-view-storagegrid.html
    - title: Faites confiance aux services de données NetApp avec StorageGRID
      url: task-enable-data-services.html
    - title: Déposer StorageGRID
      url: task-remove-storagegrid.html
  - title: Plus d'informations
    links:
    - title: Documentation StorageGRID pour la gestion en dehors de BlueXP
      url: https://docs.netapp.com/us-en/storagegrid-116/
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://cloud.netapp.com/blog
    - title: Webinaires sur le cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
