---
sidebar: sidebar 
permalink: reference-known-issues.html 
keywords: issues, known issues, bugs, errors 
summary: 'Les problèmes connus identifient les problèmes susceptibles de vous empêcher d"utiliser cette version du produit avec succès.' 
---
= Problèmes connus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les problèmes connus identifient les problèmes susceptibles de vous empêcher d'utiliser cette version du produit avec succès.



== Les noms d'affichage mis à jour n'apparaissent pas dans BlueXP 

Si vous utilisez la procédure renommer pour définir un nouveau nom d'affichage pour un site ou une grille, le nouveau nom d'affichage n'est pas reflété dans l'environnement de travail BlueXP . L'environnement de travail continue d'afficher le nom du système et non le nouveau nom d'affichage.



== Erreur lors du filtrage des alertes

Lorsque vous utilisez la vue avancée, le filtrage du contenu de la page alertes entraîne une erreur.



== Erreur lors de la modification de la connexion de fédération de grille

Lors de l'utilisation de la vue avancée, il se peut que vous rencontriez une erreur de délai d'expiration de passerelle lors de la modification d'une connexion de fédération de grille.
