---
sidebar: sidebar 
permalink: task-enable-data-services.html 
keywords: storagegrid, cloud sync, cloud backup, backup, back up data, tier data, data tiering, tiering to storagegrid 
summary: Une fois que vous avez identifié un système StorageGRID dans BlueXP , vous pouvez utiliser les services de données de NetApp pour les sauvegardes, le Tiering des données et la synchronisation des données. 
---
= Faites confiance aux services de données NetApp avec StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois que vous avez identifié un système StorageGRID dans BlueXP , vous pouvez utiliser les services de données de NetApp pour les sauvegardes, le Tiering des données et la synchronisation des données.

* Utilisez la sauvegarde et la restauration BlueXP pour sauvegarder les données de vos systèmes ONTAP sur site vers le stockage objet de vos systèmes NetApp StorageGRID.
+
Pour commencer, accédez à l'espace de travail BlueXP et glissez-déposez un environnement de travail ONTAP sur site dans votre environnement de travail StorageGRID.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html["En savoir plus sur la sauvegarde des données ONTAP sur site dans StorageGRID"^]

* Utilisez le Tiering BlueXP  pour hiérarchiser automatiquement les données inactives des clusters ONTAP sur site vers StorageGRID.
+
Pour commencer, accédez à l'espace de travail BlueXP et glissez-déposez un environnement de travail ONTAP sur site dans votre environnement de travail StorageGRID.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-storagegrid.html["En savoir plus sur le Tiering des données à partir des clusters ONTAP sur site vers StorageGRID"^]

* Utilisez la copie et la synchronisation BlueXP pour synchroniser les données depuis ou vers un système StorageGRID.
+
Pour commencer, accédez au canevas BlueXP et glissez-déposez l'environnement de travail source sur l'environnement de travail cible. StorageGRID peut être la source ou la cible.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["En savoir plus sur la copie et la synchronisation BlueXP"^]


