---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, storagegrid' 
summary: Découvrez les nouveautés de la gestion des systèmes StorageGRID dans BlueXP. 
---
= Quelles sont les nouveautés de la gestion StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la gestion des systèmes StorageGRID dans BlueXP.



== 12 mai 2025



=== Rôles d'accès BlueXP nécessaires

Vous avez désormais besoin de l'un des rôles d'accès suivants pour afficher, découvrir ou gérer StorageGRID dans BlueXP: *Administrateur d'organisation*, *Administrateur de dossier ou de projet*, *Administrateur de stockage* ou *Spécialiste de l'état du stockage*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Découvrez les rôles d’accès BlueXP."^]



== 7 août 2024



=== Nouvelle vue avancée

À partir de StorageGRID 11.8, vous pouvez utiliser l'interface familière du Gestionnaire de grille pour gérer votre système StorageGRID à partir de BlueXP .

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Découvrez comment gérer StorageGRID à l'aide de la vue avancée"].



=== Possibilité d'examiner et d'approuver le certificat d'interface de gestion StorageGRID

Vous avez désormais la possibilité d'examiner et d'approuver un certificat d'interface de gestion StorageGRID lors de la découverte du système StorageGRID à partir de BlueXP . Vous pouvez également vérifier et approuver le dernier certificat d'interface de gestion StorageGRID sur une grille découverte.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Découvrez comment vérifier et approuver le certificat du serveur lors de la découverte du système."]



== 18 septembre 2022



=== Prise en charge de StorageGRID

Vous pouvez désormais découvrir vos systèmes StorageGRID directement depuis BlueXP. La découverte de StorageGRID vous offre une vue complète sur les données dans l'ensemble de votre environnement multicloud hybride.
